-- Generated by scripts/update.lua
-- Maps server names to their filetypes from nvim-lspconfig
return {
  ada_ls = {
    "ada"
  },
  agda_ls = {
    "agda"
  },
  aiken = {
    "aiken"
  },
  air = {
    "r"
  },
  alloy_ls = {
    "alloy"
  },
  anakin_language_server = {
    "python"
  },
  angularls = {
    "typescript",
    "html",
    "typescriptreact",
    "typescript.tsx",
    "htmlangular"
  },
  ansiblels = {
    "yaml.ansible"
  },
  antlersls = {
    "html",
    "antlers"
  },
  apex_ls = {
    "apex",
    "apexcode"
  },
  arduino_language_server = {
    "arduino"
  },
  asm_lsp = {
    "asm",
    "vmasm"
  },
  ast_grep = {
    "bash",
    "c",
    "cpp",
    "csharp",
    "css",
    "elixir",
    "go",
    "haskell",
    "html",
    "java",
    "javascript",
    "javascriptreact",
    "javascript.jsx",
    "json",
    "kotlin",
    "lua",
    "nix",
    "php",
    "python",
    "ruby",
    "rust",
    "scala",
    "solidity",
    "swift",
    "typescript",
    "typescriptreact",
    "typescript.tsx",
    "yaml"
  },
  astro = {
    "astro"
  },
  atlas = {
    "atlas-*"
  },
  atopile = {
    "ato"
  },
  autohotkey_lsp = {
    "autohotkey"
  },
  autotools_ls = {
    "config",
    "automake",
    "make"
  },
  awk_ls = {
    "awk"
  },
  azure_pipelines_ls = {
    "yaml"
  },
  bacon_ls = {
    "rust"
  },
  ballerina = {
    "ballerina"
  },
  basedpyright = {
    "python"
  },
  bashls = {
    "bash",
    "sh"
  },
  bazelrc_lsp = {
    "bazelrc"
  },
  beancount = {
    "beancount",
    "bean"
  },
  bicep = {
    "bicep",
    "bicep-params"
  },
  biome = {
    "astro",
    "css",
    "graphql",
    "html",
    "javascript",
    "javascriptreact",
    "json",
    "jsonc",
    "svelte",
    "typescript",
    "typescript.tsx",
    "typescriptreact",
    "vue"
  },
  bitbake_language_server = {
    "bitbake"
  },
  blueprint_ls = {
    "blueprint"
  },
  bqls = {
    "sql"
  },
  bright_script = {
    "brs"
  },
  brioche = {
    "brioche"
  },
  bsl_ls = {
    "bsl",
    "os"
  },
  buck2 = {
    "bzl"
  },
  buddy_ls = {
    "mlir"
  },
  buf_ls = {
    "proto"
  },
  bzl = {
    "bzl"
  },
  c3_lsp = {
    "c3",
    "c3i"
  },
  cairo_ls = {
    "cairo"
  },
  ccls = {
    "c",
    "cpp",
    "objc",
    "objcpp",
    "cuda"
  },
  cds_lsp = {
    "cds"
  },
  cir_lsp_server = {
    "cir"
  },
  ["circom-lsp"] = {
    "circom"
  },
  clangd = {
    "c",
    "cpp",
    "objc",
    "objcpp",
    "cuda"
  },
  clarinet = {
    "clar",
    "clarity"
  },
  clojure_lsp = {
    "clojure",
    "edn"
  },
  cmake = {
    "cmake"
  },
  cobol_ls = {
    "cobol"
  },
  codebook = {
    "c",
    "css",
    "gitcommit",
    "go",
    "haskell",
    "html",
    "java",
    "javascript",
    "javascriptreact",
    "lua",
    "markdown",
    "php",
    "python",
    "ruby",
    "rust",
    "toml",
    "text",
    "typescript",
    "typescriptreact"
  },
  coffeesense = {
    "coffee"
  },
  coq_lsp = {
    "coq"
  },
  crystalline = {
    "crystal"
  },
  csharp_ls = {
    "cs"
  },
  css_variables = {
    "css",
    "scss",
    "less"
  },
  cssls = {
    "css",
    "scss",
    "less"
  },
  cssmodules_ls = {
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  },
  cucumber_language_server = {
    "cucumber"
  },
  cue = {
    "cue"
  },
  cypher_ls = {
    "cypher"
  },
  daedalus_ls = {
    "d"
  },
  dafny = {
    "dfy",
    "dafny"
  },
  dagger = {
    "cue"
  },
  dartls = {
    "dart"
  },
  dcmls = {
    "dart"
  },
  debputy = {
    "debcontrol",
    "debcopyright",
    "debchangelog",
    "autopkgtest",
    "make",
    "yaml"
  },
  denols = {
    "javascript",
    "javascriptreact",
    "javascript.jsx",
    "typescript",
    "typescriptreact",
    "typescript.tsx"
  },
  dhall_lsp_server = {
    "dhall"
  },
  diagnosticls = {},
  digestif = {
    "tex",
    "plaintex",
    "context"
  },
  djls = {
    "htmldjango",
    "html",
    "python"
  },
  djlsp = {
    "html",
    "htmldjango"
  },
  docker_compose_language_service = {
    "yaml.docker-compose"
  },
  docker_language_server = {
    "dockerfile",
    "yaml.docker-compose"
  },
  dockerls = {
    "dockerfile"
  },
  dolmenls = {
    "smt2",
    "tptp",
    "p",
    "cnf",
    "icnf",
    "zf"
  },
  dotls = {
    "dot"
  },
  dprint = {
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "json",
    "jsonc",
    "markdown",
    "python",
    "toml",
    "rust",
    "roslyn",
    "graphql"
  },
  ds_pinyin_lsp = {
    "markdown",
    "org"
  },
  dts_lsp = {
    "dts",
    "dtsi",
    "overlay"
  },
  earthlyls = {
    "earthfile"
  },
  ecsact = {
    "ecsact"
  },
  elixirls = {
    "elixir",
    "eelixir",
    "heex",
    "surface"
  },
  elmls = {
    "elm"
  },
  elp = {
    "erlang"
  },
  ember = {
    "handlebars",
    "typescript",
    "javascript",
    "typescript.glimmer",
    "javascript.glimmer"
  },
  emmet_language_server = {
    "astro",
    "css",
    "eruby",
    "html",
    "htmlangular",
    "htmldjango",
    "javascriptreact",
    "less",
    "pug",
    "sass",
    "scss",
    "svelte",
    "templ",
    "typescriptreact",
    "vue"
  },
  emmet_ls = {
    "astro",
    "css",
    "eruby",
    "html",
    "htmlangular",
    "htmldjango",
    "javascriptreact",
    "less",
    "pug",
    "sass",
    "scss",
    "svelte",
    "templ",
    "typescriptreact",
    "vue"
  },
  emmylua_ls = {
    "lua"
  },
  erg_language_server = {
    "erg"
  },
  erlangls = {
    "erlang"
  },
  esbonio = {
    "rst"
  },
  eslint = {
    "javascript",
    "javascriptreact",
    "javascript.jsx",
    "typescript",
    "typescriptreact",
    "typescript.tsx",
    "vue",
    "svelte",
    "astro",
    "htmlangular"
  },
  expert = {
    "elixir",
    "eelixir",
    "heex",
    "surface"
  },
  facility_language_server = {
    "fsd"
  },
  fennel_language_server = {
    "fennel"
  },
  fennel_ls = {
    "fennel"
  },
  fish_lsp = {
    "fish"
  },
  flow = {
    "javascript",
    "javascriptreact",
    "javascript.jsx"
  },
  flux_lsp = {
    "flux"
  },
  foam_ls = {
    "foam",
    "OpenFOAM"
  },
  fortls = {
    "fortran"
  },
  fsautocomplete = {
    "fsharp"
  },
  fsharp_language_server = {
    "fsharp"
  },
  fstar = {
    "fstar"
  },
  futhark_lsp = {
    "futhark",
    "fut"
  },
  gdscript = {
    "gd",
    "gdscript",
    "gdscript3"
  },
  gdshader_lsp = {
    "gdshader",
    "gdshaderinc"
  },
  gh_actions_ls = {
    "yaml"
  },
  ghcide = {
    "haskell",
    "lhaskell"
  },
  ghdl_ls = {
    "vhdl"
  },
  ginko_ls = {
    "dts"
  },
  gitlab_ci_ls = {
    "yaml.gitlab"
  },
  gitlab_duo = {
    "ruby",
    "go",
    "javascript",
    "typescript",
    "typescriptreact",
    "javascriptreact",
    "rust",
    "lua",
    "python",
    "java",
    "cpp",
    "c",
    "php",
    "cs",
    "kotlin",
    "swift",
    "scala",
    "vue",
    "svelte",
    "html",
    "css",
    "scss",
    "json",
    "yaml"
  },
  glasgow = {
    "wgsl"
  },
  gleam = {
    "gleam"
  },
  glint = {
    "html.handlebars",
    "handlebars",
    "typescript",
    "typescript.glimmer",
    "javascript",
    "javascript.glimmer"
  },
  glsl_analyzer = {
    "glsl",
    "vert",
    "tesc",
    "tese",
    "frag",
    "geom",
    "comp"
  },
  glslls = {
    "glsl",
    "vert",
    "tesc",
    "tese",
    "frag",
    "geom",
    "comp"
  },
  gnls = {
    "gn"
  },
  golangci_lint_ls = {
    "go",
    "gomod"
  },
  gopls = {
    "go",
    "gomod",
    "gowork",
    "gotmpl"
  },
  gradle_ls = {
    "groovy"
  },
  grammarly = {
    "markdown"
  },
  graphql = {
    "graphql",
    "typescriptreact",
    "javascriptreact"
  },
  groovyls = {
    "groovy"
  },
  guile_ls = {
    "scheme.guile"
  },
  harper_ls = {
    "asciidoc",
    "c",
    "cpp",
    "cs",
    "gitcommit",
    "go",
    "html",
    "java",
    "javascript",
    "lua",
    "markdown",
    "nix",
    "python",
    "ruby",
    "rust",
    "swift",
    "toml",
    "typescript",
    "typescriptreact",
    "haskell",
    "cmake",
    "typst",
    "php",
    "dart",
    "clojure",
    "sh"
  },
  hdl_checker = {
    "vhdl",
    "verilog",
    "systemverilog"
  },
  helm_ls = {
    "helm",
    "yaml.helm-values"
  },
  herb_ls = {
    "html",
    "eruby"
  },
  hhvm = {
    "php",
    "hack"
  },
  hie = {
    "haskell"
  },
  hlasm = {
    "hlasm"
  },
  hls = {
    "haskell",
    "lhaskell"
  },
  hoon_ls = {
    "hoon"
  },
  html = {
    "html",
    "templ"
  },
  htmx = {
    "aspnetcorerazor",
    "astro",
    "astro-markdown",
    "blade",
    "clojure",
    "django-html",
    "htmldjango",
    "edge",
    "eelixir",
    "elixir",
    "ejs",
    "erb",
    "eruby",
    "gohtml",
    "gohtmltmpl",
    "haml",
    "handlebars",
    "hbs",
    "html",
    "htmlangular",
    "html-eex",
    "heex",
    "jade",
    "leaf",
    "liquid",
    "markdown",
    "mdx",
    "mustache",
    "njk",
    "nunjucks",
    "php",
    "razor",
    "slim",
    "twig",
    "javascript",
    "javascriptreact",
    "reason",
    "rescript",
    "typescript",
    "typescriptreact",
    "vue",
    "svelte",
    "templ"
  },
  hydra_lsp = {
    "yaml"
  },
  hylo_ls = {
    "hylo"
  },
  hyprls = {
    "hyprlang"
  },
  idris2_lsp = {
    "idris2"
  },
  intelephense = {
    "php"
  },
  janet_lsp = {
    "janet"
  },
  java_language_server = {
    "java"
  },
  jdtls = {
    "java"
  },
  jedi_language_server = {
    "python"
  },
  jinja_lsp = {
    "jinja"
  },
  jqls = {
    "jq"
  },
  jsonls = {
    "json",
    "jsonc"
  },
  jsonnet_ls = {
    "jsonnet",
    "libsonnet"
  },
  julials = {
    "julia"
  },
  just = {
    "just"
  },
  kcl = {
    "kcl"
  },
  koka = {
    "koka"
  },
  kotlin_language_server = {
    "kotlin"
  },
  kotlin_lsp = {
    "kotlin"
  },
  kulala_ls = {
    "http"
  },
  laravel_ls = {
    "php",
    "blade"
  },
  lean3ls = {
    "lean3"
  },
  lelwel_ls = {
    "llw"
  },
  lemminx = {
    "xml",
    "xsd",
    "xsl",
    "xslt",
    "svg"
  },
  lexical = {
    "elixir",
    "eelixir",
    "heex",
    "surface"
  },
  lsp_ai = {},
  ltex = {
    "bib",
    "gitcommit",
    "markdown",
    "org",
    "plaintex",
    "rst",
    "rnoweb",
    "tex",
    "pandoc",
    "quarto",
    "rmd",
    "context",
    "html",
    "xhtml",
    "mail",
    "text"
  },
  ltex_plus = {
    "asciidoc",
    "bib",
    "context",
    "gitcommit",
    "html",
    "markdown",
    "org",
    "pandoc",
    "plaintex",
    "quarto",
    "mail",
    "mdx",
    "rmd",
    "rnoweb",
    "rst",
    "tex",
    "text",
    "typst",
    "xhtml"
  },
  lua_ls = {
    "lua"
  },
  luau_lsp = {
    "luau"
  },
  lwc_ls = {
    "javascript",
    "html"
  },
  m68k = {
    "asm68k"
  },
  markdown_oxide = {
    "markdown"
  },
  ["marko-js"] = {
    "marko"
  },
  marksman = {
    "markdown",
    "markdown.mdx"
  },
  matlab_ls = {
    "matlab"
  },
  mdx_analyzer = {
    "mdx"
  },
  mesonlsp = {
    "meson"
  },
  metals = {
    "scala"
  },
  millet = {
    "sml"
  },
  mint = {
    "mint"
  },
  mlir_lsp_server = {
    "mlir"
  },
  mlir_pdll_lsp_server = {
    "pdll"
  },
  mm0_ls = {
    "metamath-zero"
  },
  mojo = {
    "mojo"
  },
  motoko_lsp = {
    "motoko"
  },
  move_analyzer = {
    "move"
  },
  msbuild_project_tools_server = {
    "msbuild"
  },
  muon = {
    "meson"
  },
  mutt_ls = {
    "muttrc",
    "neomuttrc"
  },
  nelua_lsp = {
    "nelua"
  },
  neocmake = {
    "cmake"
  },
  nextflow_ls = {
    "nextflow"
  },
  nextls = {
    "elixir",
    "eelixir",
    "heex",
    "surface"
  },
  nginx_language_server = {
    "nginx"
  },
  nickel_ls = {
    "ncl",
    "nickel"
  },
  nil_ls = {
    "nix"
  },
  nim_langserver = {
    "nim"
  },
  nimls = {
    "nim"
  },
  nixd = {
    "nix"
  },
  nomad_lsp = {
    "hcl.nomad",
    "nomad"
  },
  ntt = {
    "ttcn"
  },
  nushell = {
    "nu"
  },
  nxls = {
    "json",
    "jsonc"
  },
  ocamllsp = {
    "ocaml",
    "menhir",
    "ocamlinterface",
    "ocamllex",
    "reason",
    "dune"
  },
  ols = {
    "odin"
  },
  omnisharp = {
    "cs",
    "vb"
  },
  opencl_ls = {
    "opencl"
  },
  openscad_ls = {
    "openscad"
  },
  openscad_lsp = {
    "openscad"
  },
  oxlint = {
    "javascript",
    "javascriptreact",
    "javascript.jsx",
    "typescript",
    "typescriptreact",
    "typescript.tsx"
  },
  pact_ls = {
    "pact"
  },
  pasls = {
    "pascal"
  },
  pbls = {
    "proto"
  },
  perlls = {
    "perl"
  },
  perlnavigator = {
    "perl"
  },
  perlpls = {
    "perl"
  },
  pest_ls = {
    "pest"
  },
  phan = {
    "php"
  },
  phpactor = {
    "php"
  },
  phptools = {
    "php"
  },
  pico8_ls = {
    "p8"
  },
  please = {
    "bzl"
  },
  pli = {
    "pli"
  },
  poryscript_pls = {
    "pory"
  },
  postgres_lsp = {
    "sql"
  },
  powershell_es = {
    "ps1"
  },
  prismals = {
    "prisma"
  },
  prolog_ls = {
    "prolog"
  },
  prosemd_lsp = {
    "markdown"
  },
  protols = {
    "proto"
  },
  psalm = {
    "php"
  },
  pug = {
    "pug"
  },
  puppet = {
    "puppet"
  },
  purescriptls = {
    "purescript"
  },
  pylsp = {
    "python"
  },
  pylyzer = {
    "python"
  },
  pyre = {
    "python"
  },
  pyrefly = {
    "python"
  },
  pyright = {
    "python"
  },
  qmlls = {
    "qml",
    "qmljs"
  },
  quick_lint_js = {
    "javascript",
    "typescript"
  },
  r_language_server = {
    "r",
    "rmd",
    "quarto"
  },
  racket_langserver = {
    "racket",
    "scheme"
  },
  raku_navigator = {
    "raku"
  },
  reason_ls = {
    "reason"
  },
  regal = {
    "rego"
  },
  regols = {
    "rego"
  },
  remark_ls = {
    "markdown"
  },
  rescriptls = {
    "rescript"
  },
  rls = {
    "rust"
  },
  rnix = {
    "nix"
  },
  robotcode = {
    "robot",
    "resource"
  },
  robotframework_ls = {
    "robot"
  },
  roc_ls = {
    "roc"
  },
  rome = {
    "javascript",
    "javascriptreact",
    "json",
    "typescript",
    "typescript.tsx",
    "typescriptreact"
  },
  roslyn_ls = {
    "cs"
  },
  rpmspec = {
    "spec"
  },
  rubocop = {
    "ruby"
  },
  ruby_lsp = {
    "ruby",
    "eruby"
  },
  ruff = {
    "python"
  },
  ruff_lsp = {
    "python"
  },
  rumdl = {
    "markdown"
  },
  rune_languageserver = {
    "rune"
  },
  rust_analyzer = {
    "rust"
  },
  salt_ls = {
    "sls"
  },
  scheme_langserver = {
    "scheme"
  },
  scry = {
    "crystal"
  },
  selene3p_ls = {
    "lua"
  },
  serve_d = {
    "d"
  },
  shopify_theme_ls = {
    "liquid"
  },
  sixtyfps = {
    "sixtyfps"
  },
  slangd = {
    "hlsl",
    "shaderslang"
  },
  slint_lsp = {
    "slint"
  },
  smarty_ls = {
    "smarty"
  },
  smithy_ls = {
    "smithy"
  },
  snakeskin_ls = {
    "ss"
  },
  snyk_ls = {
    "go",
    "gomod",
    "javascript",
    "typescript",
    "json",
    "python",
    "requirements",
    "helm",
    "yaml",
    "terraform",
    "terraform-vars"
  },
  solang = {
    "solidity"
  },
  solargraph = {
    "ruby"
  },
  solc = {
    "solidity"
  },
  solidity = {
    "solidity"
  },
  solidity_ls = {
    "solidity"
  },
  solidity_ls_nomicfoundation = {
    "solidity"
  },
  somesass_ls = {
    "scss",
    "sass"
  },
  sorbet = {
    "ruby"
  },
  sourcekit = {
    "swift",
    "objc",
    "objcpp",
    "c",
    "cpp"
  },
  spectral = {
    "yaml",
    "json",
    "yml"
  },
  spyglassmc_language_server = {
    "mcfunction"
  },
  sqlls = {
    "sql",
    "mysql"
  },
  sqls = {
    "sql",
    "mysql"
  },
  sqruff = {
    "sql"
  },
  standardrb = {
    "ruby"
  },
  starlark_rust = {
    "star",
    "bzl",
    "BUILD.bazel"
  },
  starpls = {
    "bzl"
  },
  statix = {
    "nix"
  },
  steep = {
    "ruby",
    "eruby"
  },
  stimulus_ls = {
    "html",
    "ruby",
    "eruby",
    "blade",
    "php"
  },
  stylelint_lsp = {
    "astro",
    "css",
    "html",
    "less",
    "scss",
    "sugarss",
    "vue",
    "wxss"
  },
  stylua = {
    "lua"
  },
  stylua3p_ls = {
    "lua"
  },
  superhtml = {
    "superhtml",
    "html"
  },
  svelte = {
    "svelte"
  },
  svlangserver = {
    "verilog",
    "systemverilog"
  },
  svls = {
    "verilog",
    "systemverilog"
  },
  swift_mesonls = {
    "meson"
  },
  syntax_tree = {
    "ruby"
  },
  systemd_ls = {
    "systemd"
  },
  tabby_ml = {},
  tailwindcss = {
    "aspnetcorerazor",
    "astro",
    "astro-markdown",
    "blade",
    "clojure",
    "django-html",
    "htmldjango",
    "edge",
    "eelixir",
    "elixir",
    "ejs",
    "erb",
    "eruby",
    "gohtml",
    "gohtmltmpl",
    "haml",
    "handlebars",
    "hbs",
    "html",
    "htmlangular",
    "html-eex",
    "heex",
    "jade",
    "leaf",
    "liquid",
    "markdown",
    "mdx",
    "mustache",
    "njk",
    "nunjucks",
    "php",
    "razor",
    "slim",
    "twig",
    "css",
    "less",
    "postcss",
    "sass",
    "scss",
    "stylus",
    "sugarss",
    "javascript",
    "javascriptreact",
    "reason",
    "rescript",
    "typescript",
    "typescriptreact",
    "vue",
    "svelte",
    "templ"
  },
  taplo = {
    "toml"
  },
  tblgen_lsp_server = {
    "tablegen"
  },
  tclsp = {
    "tcl",
    "sdc",
    "xdc",
    "upf"
  },
  teal_ls = {
    "teal"
  },
  templ = {
    "templ"
  },
  terraform_lsp = {
    "terraform",
    "hcl"
  },
  terraformls = {
    "terraform",
    "terraform-vars"
  },
  texlab = {
    "tex",
    "plaintex",
    "bib"
  },
  textlsp = {
    "text",
    "tex",
    "org"
  },
  tflint = {
    "terraform"
  },
  theme_check = {
    "liquid"
  },
  thriftls = {
    "thrift"
  },
  tilt_ls = {
    "tiltfile"
  },
  tinymist = {
    "typst"
  },
  tofu_ls = {
    "opentofu",
    "opentofu-vars",
    "terraform"
  },
  tombi = {
    "toml"
  },
  ts_ls = {
    "javascript",
    "javascriptreact",
    "javascript.jsx",
    "typescript",
    "typescriptreact",
    "typescript.tsx"
  },
  ts_query_ls = {
    "query"
  },
  tsgo = {
    "javascript",
    "javascriptreact",
    "javascript.jsx",
    "typescript",
    "typescriptreact",
    "typescript.tsx"
  },
  tsp_server = {
    "typespec"
  },
  ttags = {
    "ruby",
    "rust",
    "javascript",
    "haskell"
  },
  turbo_ls = {
    "html",
    "ruby",
    "eruby",
    "blade",
    "php"
  },
  turtle_ls = {
    "turtle",
    "ttl"
  },
  tvm_ffi_navigator = {
    "python",
    "cpp"
  },
  twiggy_language_server = {
    "twig"
  },
  ty = {
    "python"
  },
  typeprof = {
    "ruby",
    "eruby"
  },
  typst_lsp = {
    "typst"
  },
  uiua = {
    "uiua"
  },
  ungrammar_languageserver = {
    "ungrammar"
  },
  unison = {
    "unison"
  },
  unocss = {
    "erb",
    "haml",
    "hbs",
    "html",
    "css",
    "postcss",
    "javascript",
    "javascriptreact",
    "markdown",
    "ejs",
    "php",
    "svelte",
    "typescript",
    "typescriptreact",
    "vue-html",
    "vue",
    "sass",
    "scss",
    "less",
    "stylus",
    "astro",
    "rescript",
    "rust"
  },
  uvls = {
    "uvl"
  },
  v_analyzer = {
    "v",
    "vsh",
    "vv"
  },
  vacuum = {
    "yaml.openapi",
    "json.openapi"
  },
  vala_ls = {
    "vala",
    "genie"
  },
  vale_ls = {
    "asciidoc",
    "markdown",
    "text",
    "tex",
    "rst",
    "html",
    "xml"
  },
  verible = {
    "systemverilog",
    "verilog"
  },
  veridian = {
    "systemverilog",
    "verilog"
  },
  veryl_ls = {
    "veryl"
  },
  vespa_ls = {
    "sd",
    "profile",
    "yql"
  },
  vhdl_ls = {
    "vhd",
    "vhdl"
  },
  vimls = {
    "vim"
  },
  visualforce_ls = {
    "visualforce"
  },
  vls = {
    "v",
    "vlang"
  },
  volar = {
    "vue"
  },
  vscoqtop = {
    "coq"
  },
  vsrocq = {
    "coq"
  },
  vtsls = {
    "javascript",
    "javascriptreact",
    "javascript.jsx",
    "typescript",
    "typescriptreact",
    "typescript.tsx"
  },
  vue_ls = {
    "vue"
  },
  wasm_language_tools = {
    "wat"
  },
  wc_language_server = {
    "html",
    "javascriptreact",
    "typescriptreact",
    "astro",
    "svelte",
    "vue",
    "markdown",
    "mdx",
    "javascript",
    "typescript",
    "css",
    "scss",
    "less"
  },
  wgsl_analyzer = {
    "wgsl"
  },
  yamlls = {
    "yaml",
    "yaml.docker-compose",
    "yaml.gitlab",
    "yaml.helm-values"
  },
  yang_lsp = {
    "yang"
  },
  yls = {
    "yar",
    "yara"
  },
  ziggy = {
    "ziggy"
  },
  ziggy_schema = {
    "ziggy_schema"
  },
  zk = {
    "markdown"
  },
  zls = {
    "zig",
    "zir"
  },
  zuban = {
    "python"
  }
}
