return {
  aiken = "",
  als = "",
  anakin_language_server = "",
  angularls = "",
  ansiblels = "ansible-language-server",
  antlersls = "",
  apex_ls = "",
  arduino_language_server = "arduino-language-server",
  asm_lsp = "asm-lsp",
  ast_grep = "",
  astro = "nodePackages.\"@astrojs/language-server\"",
  autotools_ls = "",
  awk_ls = "",
  azure_pipelines_ls = "",
  bashls = "nodePackages.bash-language-server",
  beancount = "beancount-language-server",
  bicep = "",
  biome = "",
  blueprint_ls = "blueprint-compiler",
  bqnlsp = "",
  bright_script = "",
  bsl_ls = "",
  buck2 = "",
  buddy_ls = "",
  bufls = "buf-language-server",
  bzl = "",
  cadence = "",
  cairo_ls = "",
  ccls = "ccls",
  cds_lsp = "",
  ["circom-lsp"] = "",
  clangd = "clang-tools_16",
  clarity_lsp = "",
  clojure_lsp = "clojure-lsp",
  cmake = "cmake-language-server",
  cobol_ls = "",
  codeqlls = "codeql",
  coffeesense = "",
  contextive = "",
  coq_lsp = "coqPackages.coq-lsp",
  crystalline = {
    "crystalline",
    "crystal"
  },
  csharp_ls = "csharp-ls",
  css_variables = "",
  cssls = "nodePackages.vscode-langservers-extracted",
  cssmodules_ls = "",
  cucumber_language_server = "",
  custom_elements_ls = "",
  cypher_ls = "",
  dafny = "",
  dagger = "cuelsp",
  dartls = "dart",
  dcmls = "",
  delphi_ls = "",
  denols = "deno",
  dhall_lsp_server = "dhall-lsp-server",
  diagnosticls = "nodePackages.diagnostic-languageserver",
  digestif = "lua54Packages.digestif",
  docker_compose_language_service = "docker-compose-language-service",
  dockerls = "nodePackages.dockerfile-language-server-nodejs",
  dolmenls = "",
  dotls = "dot-language-server",
  dprint = "",
  drools_lsp = "",
  ds_pinyin_lsp = "",
  ecsact = "",
  efm = "efm-langserver",
  elixirls = {
    "elixir_ls",
    "beamPackages.hex"
  },
  elmls = "elmPackages.elm-language-server",
  elp = "",
  ember = "",
  emmet_language_server = "",
  emmet_ls = "",
  erg_language_server = "",
  erlangls = "erlang-ls",
  esbonio = "",
  eslint = {
    "nodePackages.vscode-langservers-extracted",
    "nodePackages.eslint"
  },
  facility_language_server = "",
  fennel_language_server = "",
  fennel_ls = "fennel-ls",
  flow = "flow",
  flux_lsp = "",
  foam_ls = "",
  fortls = "fortls",
  fsautocomplete = "fsautocomplete",
  fsharp_language_server = "",
  fstar = "fstar",
  futhark_lsp = "futhark",
  gdscript = "",
  gdshader_lsp = "",
  ghcide = "",
  ghdl_ls = "",
  gleam = "gleam",
  glint = "",
  glsl_analyzer = "",
  glslls = "glslls",
  golangci_lint_ls = "",
  gopls = {
    "gopls",
    "go"
  },
  gradle_ls = "",
  grammarly = "",
  graphql = "",
  groovyls = "",
  guile_ls = "",
  harper_ls = "",
  haxe_language_server = "",
  hdl_checker = "",
  helm_ls = "helm-ls",
  hhvm = "",
  hie = "",
  hls = {
    "haskell-language-server",
    "ghc"
  },
  hoon_ls = "",
  html = "nodePackages.vscode-langservers-extracted",
  htmx = "",
  hydra_lsp = "",
  idris2_lsp = "idris2Packages.idris2Lsp",
  intelephense = "nodePackages.intelephense",
  java_language_server = "java-language-server",
  jdtls = "jdt-language-server",
  jedi_language_server = "python3Packages.jedi-language-server",
  jqls = "jq-lsp",
  jsonls = "nodePackages.vscode-langservers-extracted",
  jsonnet_ls = "jsonnet-language-server",
  julials = "",
  koka = "koka",
  kotlin_language_server = "kotlin-language-server",
  lean3ls = "",
  leanls = "",
  lelwel_ls = "",
  lemminx = "",
  lexical = "",
  ltex = "ltex-ls",
  lua_ls = "lua-language-server",
  luau_lsp = "",
  lwc_ls = "",
  m68k = "",
  markdown_oxide = "",
  marksman = "marksman",
  matlab_ls = "matlab-language-server",
  mdx_analyzer = "",
  metals = { "metals", "jdk17" },
  millet = "millet",
  mint = "mint",
  mlir_lsp_server = "",
  mlir_pdll_lsp_server = "",
  mm0_ls = "",
  mojo = "",
  move_analyzer = "",
  mutt_ls = "",
  nelua_lsp = "",
  neocmake = "",
  nginx_language_server = "",
  nickel_ls = "nls",
  nil_ls = "nil",
  nim_langserver = "nimlangserver",
  nimls = "nimlsp",
  nixd = "nixd",
  nomad_lsp = "",
  ntt = "",
  nushell = "nushell",
  nxls = "",
  ocamllsp = "ocamlPackages.ocaml-lsp",
  ols = "",
  omnisharp = {
    "omnisharp-roslyn",
    "dotnet-sdk"
  },
  opencl_ls = "",
  openedge_ls = "",
  openscad_ls = "",
  openscad_lsp = "openscad-lsp",
  pact_ls = "",
  pasls = "",
  perlls = {
    "perlPackages.PerlLanguageServer",
    "perl"
  },
  perlnavigator = {
    "perlnavigator",
    "perl"
  },
  perlpls = "perl538Packages.PLS",
  pest_ls = "",
  phan = "",
  phpactor = "phpactor",
  pico8_ls = "",
  pkgbuild_language_server = "",
  please = "",
  postgres_lsp = "postgres-lsp",
  powershell_es = "",
  prismals = "nodePackages.\"@prisma/language-server\"",
  prolog_ls = "",
  prosemd_lsp = "",
  psalm = "php80Packages.psalm",
  puppet = "",
  purescriptls = "nodePackages.purescript-language-server",
  pylsp = "python3Packages.python-lsp-server",
  pylyzer = "pylyzer",
  pyre = "",
  pyright = "pyright",
  qml_lsp = "",
  qmlls = "",
  quick_lint_js = "quick-lint-js",
  r_language_server = "rPackages.languageserver",
  racket_langserver = "",
  raku_navigator = "",
  reason_ls = "",
  regols = "regols",
  relay_lsp = "",
  remark_ls = "",
  rescriptls = "",
  rls = "",
  rnix = "rnix-lsp",
  robotframework_ls = "",
  rubocop = "",
  ruby_lsp = "rubyPackages.ruby-lsp",
  ruff_lsp = "ruff-lsp",
  rune_languageserver = "rune-languageserver",
  rust_analyzer = {
    "rust-analyzer",
    "cargo",
    "rustfmt"
  },
  salt_ls = "",
  scheme_langserver = "",
  scry = "scry",
  serve_d = "",
  sixtyfps = "",
  slangd = "",
  slint_lsp = "slint-lsp",
  smarty_ls = "",
  smithy_ls = "",
  snyk_ls = "",
  solang = "",
  solargraph = "rubyPackages.solargraph",
  solc = "solc",
  solidity = "",
  solidity_ls = "",
  solidity_ls_nomicfoundation = "",
  sorbet = "",
  sourcekit = "sourcekit-lsp",
  sourcery = "",
  spectral = "",
  spyglassmc_language_server = "",
  sqlls = "",
  standardrb = "",
  starlark_rust = "",
  statix = "",
  steep = "",
  stimulus_ls = "",
  stylelint_lsp = "",
  svelte = "nodePackages.svelte-language-server",
  svlangserver = "",
  svls = "svls",
  swift_mesonls = "",
  syntax_tree = "rubyPackages.syntax_tree",
  tabby_ml = "",
  tailwindcss = "nodePackages.\"@tailwindcss/language-server\"",
  taplo = "taplo-lsp",
  tblgen_lsp_server = "",
  teal_ls = "luajitPackages.teal-language-server",
  templ = "",
  terraform_lsp = "terraform-lsp",
  terraformls = "terraform-ls",
  texlab = "texlab",
  textlsp = "",
  tflint = "tflint",
  theme_check = "",
  thriftls = "",
  tilt_ls = "tilt",
  tsserver = {
    "nodePackages.typescript-language-server",
    "nodePackages.typescript"
  },
  ttags = "",
  turtle_ls = "",
  twiggy_language_server = "",
  typeprof = "",
  typos_lsp = "",
  typst_lsp = "typst-lsp",
  uiua = "",
  unison = "",
  unocss = "",
  uvls = "",
  v_analyzer = "",
  vala_ls = "vala-language-server",
  vale_ls = "",
  vdmj = "",
  verible = "verible",
  veridian = "",
  veryl_ls = "",
  vhdl_ls = "vhdl-ls",
  vimls = "nodePackages.vim-language-server",
  visualforce_ls = "",
  vls = "vlang",
  volar = "nodePackages.\"@volar/vue-language-server\"",
  vtsls = "",
  vuels = "nodePackages.vue-language-server",
  wgsl_analyzer = "",
  yamlls = "nodePackages.yaml-language-server",
  yang_lsp = "",
  yls = "",
  zk = "zk",
  zls = "zls"
}
