#!/usr/bin/env -S nvim -l

local serpent = require("serpent")

vim.opt.rtp:append("tmp/nvim-lspconfig")

local lsp_directory = 'tmp/nvim-lspconfig/lsp'
local configurations_directories = {
  'tmp/nvim-lspconfig/lua/lspconfig/configs',
  lsp_directory
}

-- == Generate servers packages mapping ==

local servers_file = 'lua/lazy-lsp/servers.lua'
local lazy_servers = dofile(servers_file)
local servers = {}

for _, configurations_directory in ipairs(configurations_directories) do
  local pfile = assert(io.popen("ls '" .. configurations_directory .. "'"))
  for filename in pfile:lines() do
    local server = filename:gsub('%.lua$', '')
    servers[server] = ""
  end
  pfile:close()
end

for k, v in pairs(lazy_servers) do
  local server_exists_in_lspconfig = servers[k]
  local nix_pkg_defined = v ~= ""
  if server_exists_in_lspconfig and nix_pkg_defined then
    servers[k] = v
  end
end

-- Remove following so that they are not automatically added which would cause warning messages on neovim startup
local ignored = {
  "rome", "sqls", "ocamlls", "rnix", "als", "bufls", "ruff_lsp",
  "typst_lsp", -- deprecated in favor of tinymist and archived on Nov 5, 2024
  "vuels",     -- deprecated in favor of volar
  "volar",     -- deprecated in favor of vue_ls
}
print("Ignoring deprecated:", table.concat(ignored, ", "))
for _, v in ipairs(ignored) do
  servers[v] = nil
end

local f = assert(io.open(servers_file, 'w'))
f:write('return ' .. serpent.block(servers, { comment = false }) .. '\n')
f:close()

-- == Generate filetypes mapping ==
local filetypes_file = 'lua/lazy-lsp/filetypes.lua'
local filetypes = {}

local pfile = assert(io.popen("ls '" .. lsp_directory .. "'"))
for filename in pfile:lines() do
  local server = filename:gsub('%.lua$', '')
  local filepath = lsp_directory .. '/' .. filename
  local ok, config = pcall(dofile, filepath)
  if ok and type(config) == "table" and config.filetypes then
    filetypes[server] = config.filetypes
  end
end
pfile:close()

f = assert(io.open(filetypes_file, 'w'))
f:write('-- Generated by scripts/update.lua\n')
f:write('-- Maps server names to their filetypes from nvim-lspconfig\n')
f:write('return ' .. serpent.block(filetypes, { comment = false }) .. '\n')
f:close()

print("Generated " .. filetypes_file .. " with " .. vim.tbl_count(filetypes) .. " servers")
