name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
      - dev
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false
    - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Prepare Nix deps
      run: nix-shell --run "nvim --version"
    - name: Run tests
      run: nix-shell --run "bb test:once"
    - name: Check formatting
      run: nix-shell --run scripts/fmt


